### ISSUE TITLE
buildType: types generates non-existing import

### ISSUE THREAD

**Issue by swsnr** [sammydre/ts-for-gir#101]
This configuration:

```
{
  "environments": ["gjs"],
  "modules": ["Gio-2.0"],
  "prettify": true,
  "buildType": "types",
  "useNamespaces": true,
  "outdir": "./types/gir"
}
```

generates a `Gio-2.0.d.ts` file which in turn declares a namespace `Gio`.  The generated `index.d.ts` then roughly does this

```
import type Gio20 from "./Gio-2.0.js";
[…]
declare global {
const imports = typeof Gjs & {
  gi {
    Gio: typeof Gio20
   […]
  }
}

```

Due to the additional namespace in `Gio-2.0.d.ts` this declaration puts the Gio members under `imports.gi.Gio.Gio`, when in Gjs they should actually be in `imports.gi.Gio`.    `imports.gi.Gio.Gio` just never exists in Gjs.

With `buildType: lib` it works.

What am I doing wrong?

**Comment by JumpLink** [comment]
Hi @swsnr , sounds like a bug, I will check this. Thank you for report

**Comment by swsnr** [comment]
Thank you for taking a look 🙏🏿

**Comment by JumpLink** [comment]
@swsnr I could not find any types like `imports.gi.Gio.Gio`, but I found another bug and created [an example with your config](https://github.com/sammydre/ts-for-gir/tree/master/examples/Gjs/gio-2-cat-types-only). Please note that you need to write `useNamespace` instead of `useNamespaces` in your config. I hope this helps.

**Comment by swsnr** [comment]
@JumpLink Thank you very much.  Would you mind to push an update to NPM? 😇

**Comment by JumpLink** [comment]
Yea, as soon as the test passes :)

**Comment by JumpLink** [comment]
@swsnr done

**Comment by swsnr** [comment]
This fixed my issue (I think the missing default export was the key), but with the new version I also have types for Gnome Shell in the generated `index.d.ts`.

That's nice for shell extensions, of course, but in a plain Gjs environment these types don't exist.  Would you mind to make these configurable?

**Comment by JumpLink** [comment]
@swsnr yes i will make this configurable, currently there is not much in it, so this should not be an oberhead

**Comment by swsnr** [comment]
@JumpLink Thanks :)  I'm not so much concerned with overhead, but with having correct types, i.e. not have types for something that doesn't exist 😇   Omitting the shell types in a plain Gjs environment also improves auto-completion in editors, by offering less options 🙂

**Comment by JumpLink** [comment]
@swsnr Yes I agree 👍
