### ISSUE TITLE
Interfaces

### ISSUE THREAD

**Issue by realh** [sammydre/ts-for-gir#13]
GObject interfaces being exported as TS classes instead of interfaces can be an inconvenience, requiring one to override type safety with explicit casts.

For usability it would be best if the TS definition referred to a TS interface, ie simply change `class` to `interface`. However, that would hide the JS object we need to use to initialise classes that implement GInterfaces. But they could still be accessed by looking up the names as strings in imports.gi.*. When a new decorator-based API is designed to replace `GObject.registerClass` there's an opportunity to make this a non-issue by making the `g_implements` (or whatever it ends up being called) decorator accept a string as an alternative to a class.

**Comment by JumpLink** [comment]
A decorator based API would be very nice, but I think it will be a long time before ECMAScript decorators are included in the standard.

Conveniently, we are in the TypeScript world where decorators have been used for a long time. So I would like to develop a TypeScript framework where we could implement decorators for GObject classes ourselves. Then it would probably not be a problem anymore if GObject interfaces are also generated as Typescript interfaces.

So the question is, do we want to implement that here or in a separate framework and do we want to continue to support interfaces as classes in ts-for-gir then?

**Comment by realh** [comment]
I've written my own decorators. They would need some work to make them suitable for "production", but they might make a useful starting point.

[gdeco.js](https://github.com/sammydre/ts-for-gir/files/8427508/gdeco.js.txt)
[gdeco.d.ts](https://github.com/sammydre/ts-for-gir/files/8427507/gdeco.d.ts.txt)

I think the gjs developers are open to improving the API for class registration etc in a way that's forward compatible with decorators, so you could try liaising with them.

**Comment by realh** [comment]
On the subject of interfaces as classes, I found that when you define a class in Typescript, it automatically creates an interface with the same name, so you might as well continue to treat them as TS classes, making it easier to support static methods etc. For my inheritance fork, there is effectively no distinction between GObject classes and interfaces. Each one is declared both as a TS interface containing the instance methods and properties, and a TS object (not a class) containing the static methods etc. This almost completely solves the problem with clashing overloads, but there are a few cases that need workarounds.

**Comment by JumpLink** [comment]
Thanks a lot, I think this information will help me a lot to be able to implement the whole thing, I will also take a closer look at your fork as soon as I tackle this.

Submitting the decorators directly to Gjs is a good idea, but I will have to experiment with it myself beforehand to provide a clean implementation.

I find the [following project very interesting](https://deepkit.io/blog/introducing-deepkit-framework), this provides the Typescript types at runtime and builds a framework on top of it which uses the types e.g. for dependency injection. I would like to experiment with this, it might be cool to combine registering GObject classes with decorators and dependency injection.

But I'm not sure yet if that might not be too much, what do you think?

**Comment by JumpLink** [comment]
You can ignore the stack trace, decisive is the message "No module found", which means that no gir files were found that you are looking for. So maybe you need to set --girDirectories. You can use the `list` command to see what modules are found.

Btw. In the current version i have replaced `@oclif` with [yargs](http://yargs.js.org/) since yargs also supports deno and is less confusing

**Comment by realh** [comment]
Ah, OK, that'll be because I'm trying to run it on a Mac at the moment. I installed the g* packages with homebrew, which uses /usr/local on Intel (unless they changed that too, but only for fresh installs so it doesn't break existing setups), but switched to /opt/homebrew for the M1 version. IIRC brew's gobject-introspection package used to return an incorrect value for `pkg-config --variable=girdir gobject-introspection-1.0` but that seems to be fixed now. It would be nice if meson's gnome plugin could use pkg-config to choose default install locations for that sort of thing, but I'm not sure that allowing installation outside of ${prefix} is such a good idea.

**Comment by JumpLink** [comment]
Okay now inheritance and implementations are merged to master :)

**Comment by JumpLink** [comment]
@realh Can you test if this solves this issue now?
