### ISSUE TITLE
`Gio-2.0.Cancellable.connect` is typed incorrectly for GJS

### ISSUE THREAD

**Issue by HeavenVolkoff** [sammydre/ts-for-gir#87]
Hello,

Currently, the generated definitions for `Gio-2.0` on GJS has incorrect typing for the `Cancellable.connect` method according to GJS's [documentation](https://gjs-docs.gnome.org/gio20~2.66p/gio.cancellable#method-connect) and directly testing on its REPL:
![image](https://user-images.githubusercontent.com/9082460/190839443-d3563530-22a4-4e19-a5ef-fee74476b160.png)

It seems `Gio-2.0.Cancellable` doesn't follow the `GObject.connect` convention and implements a custom `connect` as far as I could understand.

To solve this I tried to simply [implement an injection into  `Gio-2.0.Cancellable` to override the `connect` method](https://github.com/sammydre/ts-for-gir/commit/4ffc6d8be63f69bf8da5c48cebfbd8347a5ce97f), however that resulted in unresolved conflicts and ultimately all implementations of `Gio-2.0.Cancellable.connect` ended up commented out of the type definitiondue to conflicts:
![image](https://user-images.githubusercontent.com/9082460/190839556-3693c767-7585-42e1-8b0e-9f358ca99158.png)

I then tried to understand why this was happening in [`conflict-resolver.ts`](/sammydre/ts-for-gir/blob/master/packages/cli/src/conflict-resolver.ts), and from what I could gather this seems to be a temporary solution:
 https://github.com/sammydre/ts-for-gir/blob/bdfd98a5654a8ffcaafe623ae123981ad39429d1/packages/cli/src/type-definition-generator.ts#L545-L548
 
I don't know if the injection solution and solving the current method conflict shortcoming is the correct path for this particular problem, or if there is some other, simpler, way. Maybe this could be solved by adding an exception on commenting out conflicting _injected_ methods? Any ideas?

**Comment by HeavenVolkoff** [comment]
I was able to make the injection solution work by adding the exception on commenting out conflicting injected methods, and using an override to the connect method, it doesn't exactly match the runtime behaviour, but at least it does not complain on correct code anymore:
https://github.com/sammydre/ts-for-gir/compare/master...HeavenVolkoff:ts-for-gir:fix-gio-cancellable-connect

I don't know if this is a scalable approach to this type of problem. However, considering it originates from Gio.Cancellable basically breaking Liskov substitution principle and Typescript type system being quite strict about it, I couldn't think of any other way that wasn't extremely hacky or ovely rcomplicated.

**Comment by JumpLink** [comment]
@HeavenVolkoff Maybe we can introduce a new property: `ignoreConflict` and if this is set write a `// @ts-ignore` over the generated type definition.

I think your approach is right, that own overrides should have a hearing priority and should not be commented out.

I'm not at the computer right now so I can't try it myself but next week I might get to it.

**Comment by HeavenVolkoff** [comment]
@JumpLink I don't think the `// @ts-ignore` solution is going to work.

When removing the overload from the `Gio.Cancelled.connect` method, Typescript complains that the whole class, and interface, incorrectly extends the base class:
![image](https://user-images.githubusercontent.com/9082460/192080296-3ebd70b1-6ce2-49e0-9181-7ad442c1569f.png)
![image](https://user-images.githubusercontent.com/9082460/192080298-f0219e9c-63b4-47a7-9f91-dcdee50ecd81.png)

Because the error is for the whole class, even when you annotate the `Gio.Cancelled.connect` method with `// @ts-ignore` the errors are not ignored. The only way to make TS ignore them is to apply the `// @ts-ignore` annotation top-level to both the class and the interface:
![image](https://user-images.githubusercontent.com/9082460/192080446-ad381c9f-d4cd-4996-8ba5-ad36c35d9b6b.png)

However, I don't personally think this is a good solution, because it can hide errors that spawn from future changes in the generator, and can, possibly, also affect how typescript type checks user projects.

I don't think my current approach is a great one, but for now is the one with fewer drawbacks that I could come up if. I will open a draft PR with it, so you can take a better look and if you think of something better feel free to commit to the PR directly.

**Comment by HeavenVolkoff** [comment]
A partial solution, that could be implemented in a future `init` command, would be to use [ESLint's `no-restricted-syntax`](https://eslint.org/docs/latest/rules/no-restricted-syntax) custom rules to warn users that calling `.connect('cancelled', () => {})` is possibly wrong if the object is a `Gio.Cancelled` instance. Which is something GJS already does in their ESLint config:
https://gitlab.gnome.org/GNOME/gjs/-/blob/master/.eslintrc.yml#L145-161

**Comment by HeavenVolkoff** [comment]
Issue resolved by PR #91, with some caveats yet to be addressed, described in #92 and #93

**Comment by JumpLink** [comment]
@HeavenVolkoff Thank you! I'll look at it next week, this one I was very busy
