### ISSUE TITLE
Extending classes derived from GObject

### ISSUE THREAD

**Issue by realh** [sammydre/ts-for-gir#9]
Examples and documentation for gjs all seem to say that when extending a class derived from GObject you should use a method called `_init` instead of constructors. But ts-for-gjs doesn't expose any `_init` methods. `GObject.registerClass` isn't exposed either. So does ts-for-gjs not support creating GObject subclasses? For most cases I suppose you can just extend the ts/js class without creating a new GObject class. In that case can a constructor parameter object be used to to initialise GObject properties? This system is limited though because you can't define your own properties, signals etc or implement additional GInterfaces. So I think we really need `_init` and `registerClass`.

**Comment by sammydre** [comment]
I never actually got GObject subclasses working myself, so there has been no explicit support here for this.

Therefore I can't really comment on the correct way of doing things!

**Comment by realh** [comment]
I've added these to my fork, in branch [register_class](https://github.com/realh/ts-for-gjs/tree/register_class). I've barely tested it though, so it's probably not ready for a PR yet.

**Comment by JumpLink** [comment]
This is already fixed. By the way, since Gjs 1.72.0 normal `constructors` can be used instead of `_init`.
